using Unity.Entities;
using Unity.Services.Authentication;
using UnityEngine;
using UnityEngine.InputSystem;
using UnityEngine.SceneManagement;
using UnityEngine.UI;

public class MainGameManger : MonoBehaviour
{
    [SerializeField] private GameObject[] playerPrefab = default; //Player
    [SerializeField] private GameObject botPrefab = default;

    [SerializeField] private Transform[] pos = default;         //生成位置

    [SerializeField] private GameObject joinobj;

  
    void Start()
    {
        joinobj = GameObject.Find("JoinedManager");
        //インスタンスがない場合はreturn
        if(PlayerDataHolder.Instance == null) { return; }

        //インスタンスで保持しているデバイス情報と人数を取得
        var devices = PlayerDataHolder.Instance.GetDevices();
        int count   = PlayerDataHolder.Instance.GetPlayerCount();

        //------------
  
              
        


        //人数分Playerの生成,PlayerID
        for (int i = 0; i < pos.Length; i++)
        {
            if(i <  count && devices[i] != null)
            {
                // 指定デバイスで PlayerInput を持つプレイヤーを生成
                var obj = PlayerInput.Instantiate(
                    prefab: playerPrefab[i],
                    playerIndex: i,
                    pairWithDevice: devices[i]
                 );
                //生成後この位置にセット
                obj.transform.position = pos[i].position;
                obj.transform.rotation = pos[i].rotation;

            }
            else
            {
                Instantiate(botPrefab, pos[i].position, pos[i].rotation);
            }
        }
    }

    // Update is called once per frame
    void Update()
    {
        
    }

    public void OnReset()
    {
        SceneManager.LoadScene("Start");
        Destroy( joinobj );   
    }
}
