using System.Collections;
using UnityEngine;
using UnityEngine.UI;

public class PowerMeter : MonoBehaviour
{
    [SerializeField] private Image MeterImage;

    [SerializeField] private float MaxChargeTime = 1.5f;

    private PlayerController pc;


    private void Start()
    {
        pc = GetComponent<PlayerController>();
        MeterImage.fillAmount = 0;
    }

    private void Update()
    {
        float speed = 1f / MaxChargeTime;
        if(pc.isPrese)
        {
            MeterImage.fillAmount += speed * Time.deltaTime;
        }
        else if(!pc.isPrese) 
        {
            MeterImage.fillAmount = 0;
        }

        // 0〜1 の範囲に制限
        MeterImage.fillAmount = Mathf.Clamp01(MeterImage.fillAmount);

        if (MeterImage.fillAmount == 1)
        {
            Debug.Log("100");
            pc.SetCharge(true);
        }
       /* else
        {
            Debug.Log("0");
            pc.SetCharge(false);
        }*/
            // Player のタックル力 (t) に反映
           
    }
}
